dataSourceClassName=org.mariadb.jdbc.MariaDbDataSource
dataSource.user=nitram_eco_user
dataSource.password=eco_password
dataSource.databaseName=nitram_eco
dataSource.portNumber=3306
dataSource.serverName=localhost