jdbcUrl = jdbc:mariadb://localhost:3306/nitram_eco
driverClassName=org.mariadb.jdbc.Driver
dataSource.user=nitram_eco_user
dataSource.password=eco_password
maximumPoolSize=10
minimumIdle=2
connectionTimeout=30000